### ISSUE TITLE
Skip intro dialogue

### ISSUE THREAD

**Issue by challenert** [challenert/digimon_world_randomizer#45]
After displaying the settings hash, the intro should simply end and jump directly to the opening scene.  Preferably would still include a dialogue to select between the two starters.  

EDIT: This is probably doable with only script, at least skipping a good chunk of the intro.

**Comment by SydMontague** [comment]
A good place to put it in is at 000424, after "Welcome to the Digital World", since there seems to be nothing potentially meaningful after it.

Adding a jumpTo 2306 should work.
-> 16 00 02 09

To skip the second part of the Intro a good place is 0002724, after "I invited you here to save us.", or any other dialogue really.
Just add a jumpTo 5108
-> 16 00 F4 13

**Comment by challenert** [comment]
Ok, I'll look into this and then we can see what happens.

**Comment by challenert** [comment]
Closing for tracking, but this is not tested yet in game.
