### ISSUE TITLE
Removing poop mechanic

### ISSUE THREAD

**Issue by SuperMintSoda** [challenert/digimon_world_randomizer#59]
Not related to the randomizer but would it be possible to turn off or freeze indefinatly the need for digimon to constantly use the bathroom?

**Comment by challenert** [comment]
Yes, this is likely possible with very little change to the code.  However, it would likely require research into ASM function that updates the condition so that it could be short-circuited with a branch.  Alternatively, it may also be possible by to achieve this by writing some value to the poop timer value in the digimon raise data table -- I'm not sure what happens if you set that to zero, for instance.

Either way, this isn't really in the spirit of what we're trying to create.  Removing core game mechanics isn't really something I'm interested in adding to the tool.  Still, this software is open source and you are welcome to fork the repo.
