### ISSUE TITLE
Different seed generation when using race log vs casual/full

### ISSUE THREAD

**Issue by RaikouSRL** [challenert/digimon_world_randomizer#74]
As it is right now, selecting race log, getting your seed and inputting the seed with casual/full log allows the runner to view the log in a random seed race file, making the output differ from set seed-casual/full and set seed-race will resolve the issue

**Comment by challenert** [comment]
The easiest and most direct way to solve this would be to check the logging type before performing any randomization.  When the logging type is 'race', advance the RNG at least one step.  That will completely change the entire randomization, thereby making it impossible to ever see the log of a race seed.

When this change is made, we should double check that log type is changing the settings hash, because with this change it will absolutely need to since it actually changes the results of the randomization.
